### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by BennieCopeland** [JordanMarr/Fable.FormValidation#1]
1. Is there a way to do live inline validation? I.e. validate a field as it's changed instead of the entire form at submission? This can provide a better user experience, especially on really big forms.
2. Can you do asynchronous validation? For example, checking that a username isn't already in use with the server?

**Comment by JordanMarr** [comment]
1. Currently no, but I will look into it. I think it should be possible to apply and check rules within the OnChange event instead of Ref with a minor change.
2. No, that is not a planned feature because that validation should happen at save time. However, you should definitely be able do it with this workflow:
    - On save, if form is valid, make call to backend api save method
    - save method should return a `Result<User, string list>` where `string list` is a collection of server side validation errors
    - Unwrap the result and display the errors in your `errorSummary` (you could use a second one if needed for server side errors)
    - If you also want to highlight a specific field in error state, you could add an `IsUsernameInUse` bool to your model and then add `CustomRule (if model.IsUsernameInUse then Error "{0} is already in use." else Ok())` to your Username field.

**Comment by BennieCopeland** [comment]
Thank you for the reply. I'm developing an Elmish app, and I've been looking to support both use cases in my forms. Something else you may want to consider is instead of returning an error string for your built-in rules to instead return a key to allow easier localization.

**Comment by JordanMarr** [comment]
Great idea. I can see how that would also be very useful.
